### ISSUE TITLE
Switch our images to webp and include caching

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#1246]
They're smaller for the same quality image.

[Converting Renditions](https://docs.wagtail.org/en/v4.0.4/advanced_topics/images/image_file_formats.html#customising-output-formats)

### Use `memcached`

**Docker**
```
memcache:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - web
      - consul
```

**base.py under CACHES**

```
"renditions": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": config("MEMCACHED_URL", "127.0.0.1:11211"),
        "TIMEOUT": 600,
    },
```

**requirements.txt**

`pymemcache>=3.5.2,<3.6` or whatever version is current

### Use `postgresql`

```
'renditions': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'wagtail_renditions_cache',
        'TIMEOUT': 86400,
    }
```
